### ISSUE TITLE
Map markers not displaying upon integrating BART API

### ISSUE THREAD

**Issue by krystynneisess** [nickfong/CS160-Collaboration#20] opened 2015-12-09 01:25 UTC
Possibly due to the BART API calls running too many processes on the main UI thread.

[integration-bart+mobile]

**Comment by nickfong** [comment] 2015-12-10 01:47
The problem hasn't been reproducible since earlier today.  Closing pending further issues with markers not loading.

**Closed by nickfong** 2015-12-10 01:47 UTC
Labels: bug
