### ISSUE TITLE
Wear pacing screens flicker between current pacing screen and a "default-ish" screen.

### ISSUE THREAD

**Issue by krystynneisess** [nickfong/CS160-Collaboration#10] opened 2015-12-05 06:41 UTC
Where the "default-ish" screen is a pacing screen characterized by:
- A green background 
- The user marker as far left as possible on the gauge
  - Note that the tick marks on the gauge, however, still reflect their correct position.
- The user time estimate at "00"
  - The train time estimate, however, still reflects the correct value.

This happens regardless of whether navigation is enabled.

[integration-bart+mobile]

**Comment by nickfong** [comment] 2015-12-08 00:56
This was reproduced (and a video was captured of this bug).  Assigning to @DaiweiLiu for further investigation.  Please see Slack for the video.

**Comment by DaiweiLiu** [comment] 2015-12-08 06:17
This is a problem on the mobile side caused by the fact that secondsRemaining can somehow oscillate between 0 and correct value. Wear side is clean.

**Comment by krystynneisess** [comment] 2015-12-09 01:05
Thanks for the update--this issues still persists on `wear-nav-fix` (which is understandable, as it has not yet been addressed).  

Assigning @packsun for investigation into the secondsRemaining value sent from mobile to wear.

**Comment by packsun** [comment] 2015-12-09 03:11
thoughts on just calculating secondsRemaining by dividing distance by 1.4 m/s rather than trying to divide by instantaneous pace? it's not like the staff will actually walk to bart just to test our app during the demo

**Comment by packsun** [comment] 2015-12-09 07:30
i saw the estimated time as 00 a few times, but i havent been able to reproduce the flickering. the "00 case" is fixed when reverting to a constant pace of 1.4 m/s rather than using instantaneous speed though

**Comment by packsun** [comment] 2015-12-09 08:31
fixed in commit a095e4f: fix pacing issues and reversed swipe behavior

**Closed by packsun** 2015-12-09 08:31 UTC
Labels: bug
